import { defineConfig } from 'eslint/config';
import { node } from '@hris/eslint-config';

export default defineConfig([
  node,
  {
    // Prisma Client is machine generated from `schema.prisma`. It is regenerated by
    // `prisma generate`, so lint findings in it are noise, and linting thousands of
    // generated lines on every run wastes the budget spent on hand written code.
    ignores: ['src/generated/**', 'dist/**', 'coverage/**', 'node_modules/**'],
  },
  {
    // Seeding and database maintenance scripts are command line tools whose entire
    // output is what they print, so `console.log` is their interface rather than stray
    // debugging. Library code under `src/` keeps the stricter rule.
    files: ['seeds/**/*.ts', 'scripts/**/*.ts'],
    rules: {
      'no-console': ['error', { allow: ['error', 'warn', 'info', 'log'] }],
    },
  },
]);
